### PR TITLE
allow ordering static dropdowns

### LINKED ISSUE #125: Field's choices aren't sorted
### Actual Behavior

The `field.choices` is required to be an `Object`, which the [ECMAScript](http://www.ecma-international.org/ecma-262/8.0/index.html) defines as not having a predictable order in the properties.

This is causing a problem with choices being rendered with random sorting sometimes.

### Expected Behavior

Choices should maintain sorting.

### Resources

- Slack convo: https://zapier-platform.slack.com/archives/C2S5DGF6G/p1503448271000081
- Private internal issue: https://github.com/zapier/zapier/issues/12998

### PR DESCRIPTION
**Pull request by xavdid**
fixes https://github.com/zapier/zapier-platform-cli/issues/125 in a less-hacky way.

Side note, this was a bear to test. Had to hack apart the CLI and server to forego any form of validation so I could figure out what structure(s) worked before writing the schema for it.

### CODE REVIEW

**Review by eliangcs — COMMENTED** [review]
This seems to be the right way to support ordered static field choices. Two questions:

1. Can we add a test for it?
2. Does the backend already support this new schema?

**Comment by xavdid** [comment]
Schema is tested via the `examples` and `antiExamples` arrays in the schema itself. The test iterates through all the schemas and makes sure that all examples validate and none of the antiExamples do ([link](https://github.com/zapier/zapier-platform-schema/blob/master/test/utils.js#L17-L18)). So each of the new ones has some simple tests built in!

Backend does support it! Once the app builds, it ships that json straight to the backend. It does server validation and then stores it. From there, it gets processed by formatic (which is the software that powers the editor). So we have to match the format it's expecting, but that's all we need. 

My app: 

screen shot 2017-12-14 at 11 12 06 am

local editor: 

screen shot 2017-12-14 at 11 12 38 am

Test result (just returns input):

screen shot 2017-12-14 at 11 13 09 am

I couldn't test against prod since the server validation uses the published version (I think), but i could disable that locally and the editor handled the json correctly.

**Review by eliangcs — APPROVED** [review]
Thanks for the clarification! I think you need to rebuild doc and schema then it's good to merge:

```
npm run docs
npm run export
```

**Comment by xavdid** [comment]
yep! i was going to let the release take care of that so the docs aren't in master before the code is deployed (which would be confusing)

**Comment by eliangcs** [comment]
@xavdid sounds good!

**Pull request merged**
