### PR TITLE
Clear ResourceSearchOrCreateSchema

### LINKED ISSUE #13: Should Resources be allowed to override the searchOrCreate
Currently the schema allows a resource to [define a searchOrCreate](https://github.com/zapier/zapier-platform-schema/blob/0589e09985a87a6967d1eca27bfb55b2b93f7dd6/lib/schemas/ResourceSchema.js#L51-L54) property, which looks like [this](https://github.com/zapier/zapier-platform-schema/blob/0589e09985a87a6967d1eca27bfb55b2b93f7dd6/lib/schemas/ResourceMethodSearchOrCreateSchema.js).

The issue is that the regular `SearchOrCreate` schema is like [this](https://github.com/zapier/zapier-platform-schema/blob/0589e09985a87a6967d1eca27bfb55b2b93f7dd6/lib/schemas/SearchOrCreateSchema.js), just defining keys of existing searches and creates to use. 

Open Questions:

 * Should a resource be allowed to overwrite this at all?
 * If so, should it be:
    * Restricted to settings keys of other searches and creates
    * Define entire operations for search and for create
    * Define a single operation? (Zapier side would need to be edited to support this)

### PR DESCRIPTION
**Pull request by kola-er**
Fixes #13

### CODE REVIEW

**Comment by kola-er** [comment]
I'm not sure if I need to write more tests in addition to the existing ones.

**Comment by ibolmo** [comment]
I believe this warrants a new label: `breaking-change` on GH? This might make it easier to tag a major version.

**Review by BrunoBernardino — APPROVED** [review]
I think this is a _safe_ change, meaning I can't think of specific useful tests to add here.

Make sure this is included in `-cli`'s `CHANGELOG`.

**Comment by kola-er** [comment]
Noted! Thanks @BrunoBernardino. I agree with you @ibolmo. I will add it.

**Review by bcooksey — APPROVED** [review]

**Pull request merged**
